name: Stage CI/CD
on:
  push:
    branches:
      - stage

  pull_request:
    branches:
      - stage

env:
  CI: false
  env_stage: ${{secrets.ENV_STAGE}}

jobs:
  build-test:
    name: install dependencies and test coverage
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: stage

      - uses: actions/setup-node@v3
        with:
          node-version: 14.17
      
      - name: create environment file
        run: |
          touch ./.env && echo "$env_stage" >> ./.env

      - name: install dependencies
        run: |
          yarn install
      
      # - name: run tests
      #   run: |
      #     yarn test
      - name: build react app
        run: |
          yarn build 
  
      - name: upload g20 vendor frontend build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: g20-vendor-build
          path: |
            build/
            conf.d/
            Dockerfile
            .dockerignore

  deploy:
    name: build docker image and push to docker hub
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14.17

      - name: download g20 vendor frontend build artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: g20-vendor-build
          
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: build and push image
        id: build-push-image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: rumsan/g20_vendor:stage

